[package]
name = "nimbus"
version = "0.1.0"
authors = ["Aravindh Sridharan <mail@aravindh.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
stopwatch = "0.0.7"
rand = "0.8.1"